"""Metodos de String"""
print('prueba'.capitalize())
print('John Eliseo'.center(20,'*'))
print('John Eliseo'.count('o'))
print('otoño'.encode('utf-8'))
print('John'.endswith('n'))
print('Carlos'.endswith('o'))
print('smartphone'.find('a'))
print('smartphone'.find('f'))
print('La casa es {}'.format('muy bonita!'))
print('automovil'.index('l'))
print('manzanas10'.isalnum())
print('pruebas string'.isalnum())
print('pruebas'.isalpha())
print('pruebas10'.isalpha())
print('10.5'.isdecimal())
print('10'.isdecimal())
print('10s'.isdigit())
print('5'.isdigit())
print('Pruebas'.islower())
print('pruebas'.islower())
print('messi 10'.isnumeric())
print('100000'.isnumeric())
print('imprimmir'.isprintable())
